use std::fmt::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    println!("hello world !!!");
    return Ok(());
}
